### ISSUE TITLE
update to remoteStorage.js 0.7.0

### ISSUE THREAD

**Issue by michielbdejong** [shared-stuff/shared-stuff.github.com#2]
Hi @shybyte,

Good news: @nilclass tagged the release of remoteStorage.js version 0.7.0 yesterday. here is an example of how it works:
https://github.com/michielbdejong/remoteStorage.js/blob/master/example/minimal/index.html
so because sync is "behind" the modules with remoteStorage.js 0.7, the app architecture is a matter of:
- putting domain code into the module (notes.js in the example)
- send controller actions to the module
- update the DOM only when the module gives you a change event

here are reference docs:
http://remotestoragejs.com/doc/code/files/remoteStorage-js.html

let me know what you think! :)

**Comment by shybyte** [comment]
I am currently travelling without a computer until 16. April.  I will update my apps to 0.7 when I'm back ASAP.

**Comment by michielbdejong** [comment]
Issue more than a year old, closing.
